/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy;

import java.sql.*;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ELTANANY 2
 */
public class recipt extends javax.swing.JFrame {

    Connection con;
    DefaultTableModel dtm;
    ArrayList<Integer> drugsID = new ArrayList<>();
    ArrayList<Integer> drugsIDOut = new ArrayList<>();
    boolean flag = false;
    int quantity;
    int i = 0;
    Double price;
    Double Total_price = 0.0;

    /**
     *
     * Creates new form recipt
     */
    public recipt() {
        initComponents();
        dtm = (DefaultTableModel) medicine_table.getModel();
        this.setLocationRelativeTo(null);

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "a01126976611as");
            fillTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Connection failed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        billid_text = new javax.swing.JTextField();
        quantity_text = new javax.swing.JTextField();
        medicine_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicine_table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        addbill_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill_list_text = new javax.swing.JTextArea();
        print_button = new javax.swing.JButton();
        print_button1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        search_fld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("receipt");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 786));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/2221.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Medicine  :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity   :");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("       Seller");

        quantity_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity_textActionPerformed(evt);
            }
        });

        medicine_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicine_textActionPerformed(evt);
            }
        });

        medicine_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "PRICE", "QUANTITY", "FAB DATE", "EXP DATE", "COMPANY"
            }
        ));
        medicine_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicine_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(medicine_table);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MEDICINE LIST ");

        addbill_button.setBackground(new java.awt.Color(204, 204, 204));
        addbill_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addbill_button.setForeground(new java.awt.Color(102, 102, 255));
        addbill_button.setText("ADD BILL");
        addbill_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbill_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(204, 204, 204));
        delete_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete_button.setForeground(new java.awt.Color(102, 102, 255));
        delete_button.setText("DELETE");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        clear_button.setBackground(new java.awt.Color(204, 204, 204));
        clear_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clear_button.setForeground(new java.awt.Color(102, 102, 255));
        clear_button.setText("CLEAR");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("        BILL LIST   ");

        bill_list_text.setColumns(20);
        bill_list_text.setRows(5);
        jScrollPane2.setViewportView(bill_list_text);

        print_button.setBackground(new java.awt.Color(204, 204, 204));
        print_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        print_button.setForeground(new java.awt.Color(102, 102, 255));
        print_button.setText("PRINT");
        print_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_buttonMouseClicked(evt);
            }
        });
        print_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_buttonActionPerformed(evt);
            }
        });

        print_button1.setBackground(new java.awt.Color(204, 204, 204));
        print_button1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        print_button1.setForeground(new java.awt.Color(102, 102, 255));
        print_button1.setText("CLOSE ");
        print_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_button1MouseClicked(evt);
            }
        });
        print_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_button1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search      :");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addbill_button)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(search_fld))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(print_button)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(122, 122, 122)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(billid_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(medicine_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quantity_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(delete_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clear_button)
                                            .addComponent(print_button1)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1)
                                        .addGap(4, 4, 4)))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(208, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(search_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(billid_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(medicine_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(quantity_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addbill_button)
                        .addComponent(clear_button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(delete_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print_button)
                    .addComponent(print_button1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addbill_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbill_buttonActionPerformed
        ResultSet rs;
        Double quant = Double.parseDouble(quantity_text.getText().toString());
        Total_price += quant * price;
        int drg_id = 0;
        String Exp_name = "";
        Double drg_price = 0.0;
        int qnt = 0;
        String cmp_name = "";

        try {
            // TODO add your handling code here:
            String txt = medicine_text.getText().toString();
            PreparedStatement stmt = con.prepareStatement("select Drugs_ID , Drugs_Quantity from drugs where Drugs_name like '" + txt + "'");
            rs = stmt.executeQuery();
            while (rs.next()) {
                i = rs.getInt(1);
                quantity = rs.getInt(2);
            }
            if (quant > 0) {
                PreparedStatement stmt453 = con.prepareStatement("INSERT INTO `project`.`sales` (`Drgs_ID` , `Purchased_quantity` ) VALUES (?,?);");

                stmt453.setInt(1, i);
                stmt453.setDouble(2, quant);
                stmt453.executeUpdate();
            }
            if (quantity == 0) {
                JOptionPane.showMessageDialog(this, "No Available Medicenes");
                PreparedStatement stmt1 = con.prepareStatement("select * from drugs;");
                ResultSet rs1;
                rs1 = stmt1.executeQuery();

                while (rs1.next()) {
                    drg_id = rs1.getInt(1);
                    Exp_name = rs1.getString(2);
                    drg_price = rs1.getDouble(3);
                    qnt = rs1.getInt(4);
                    cmp_name = rs1.getString(7);
                }

                PreparedStatement stmt3 = con.prepareStatement("INSERT INTO `project`.`out_of_stock` (`Drug_Id`, `Drugs_NameExp`, `Drug_price` , `Drug_Quantity` , `Company_Name`) VALUES (?, ?, ?,?,?);");

                stmt3.setInt(1, drg_id);
                stmt3.setString(2, Exp_name);
                stmt3.setDouble(3, drg_price);
                stmt3.setInt(4, qnt);

                stmt3.setString(5, cmp_name);

                stmt3.executeUpdate();
            } else {
                if (quantity_text.getText().isEmpty() || medicine_text.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "please put values ");
                } else {
                    if (flag == false) {
                        bill_list_text.setText(bill_list_text.getText() + "               ****************** pharmacy ****************   \n" + "                         Customer Name :      " + billid_text.getText().toString().toUpperCase() + "\n"
                                + "\t ID     MEDICINE      QUANTITY      PRICE           TOTAL \n "
                                + "                           " + i + "       " + medicine_text.getText() + "          " + quantity_text.getText() + "            " + price + "           " + price * quant + "    \n");
                        flag = true;
                    } else {
                        bill_list_text.setText(bill_list_text.getText() + "                            " + i + "       " + medicine_text.getText() + "          " + quantity_text.getText() + "            " + price + "           " + price * quant + "    \n");
                    }

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(recipt.class.getName()).log(Level.SEVERE, null, ex);
        }

        quantity -= quant;
        try {
            PreparedStatement stmt = con.prepareStatement("UPDATE `project`.`drugs` SET `Drugs_Quantity` = ? WHERE (`Drugs_ID` = ?)");
            stmt.setInt(1, quantity);
            stmt.setInt(2, i);
            stmt.executeUpdate();
            fillTable();

            //this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(recipt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addbill_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        if (!bill_list_text.getText().isEmpty()) {

            bill_list_text.setText("");
            bill_list_text.setText(bill_list_text.getText() + "               ****************** pharmacy ****************   \n" + "                         Customer Name :      " + billid_text.getText().toString().toUpperCase() + "\n"
                    + "\t ID  MEDICINE   QUANTITY   PRICE    TOTAL \n "
            );
        }

    }//GEN-LAST:event_delete_buttonActionPerformed

    private void print_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonMouseClicked
        try {
            // TODO add your handling code here:
            if (!bill_list_text.getText().isEmpty()) {
                bill_list_text.print();
            } else {
                JOptionPane.showMessageDialog(null, "nothing to print ");
            }
        } catch (PrinterException ex) {
            Logger.getLogger(recipt.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "nothing to print ");
        }
    }//GEN-LAST:event_print_buttonMouseClicked

    private void medicine_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicine_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel) medicine_table.getModel();
        int index = medicine_table.getSelectedRow();
        medicine_text.setText(mod.getValueAt(index, 1).toString());
        price = Double.parseDouble(mod.getValueAt(index, 2).toString());
        quantity_text.setText(mod.getValueAt(index, 3).toString());
    }//GEN-LAST:event_medicine_tableMouseClicked

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        medicine_text.setText("");
        quantity_text.setText("");


    }//GEN-LAST:event_clear_buttonActionPerformed

    private void print_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_buttonActionPerformed
        try {
            // TODO add your handling code here:
            ResultSet rs;
            String pharm_name = "";
            int num = 0;
            String addr = "";
            PreparedStatement stmt = con.prepareStatement("select * from pharmacy;");
            rs = stmt.executeQuery();
            while (rs.next()) {
                pharm_name = rs.getString(2);
                num = rs.getInt(3);
                addr = rs.getString(4);
            }

            if (!bill_list_text.getText().isEmpty()) {

                bill_list_text.setText(
                        bill_list_text.getText() + '\n' + "Total Pay   :  " + Total_price
                        + "\n" + "Pharmacy Name : " + pharm_name + "\n" + "Pharmacy Number : " + num + "\n" + "Pharmacy Address : " + addr
                );
            }
        } catch (SQLException ex) {
            Logger.getLogger(recipt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_print_buttonActionPerformed
    public double quantity() {

        Double quant = Double.parseDouble(quantity_text.getText().toString());
        return quant;

    }
    private void print_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_print_button1MouseClicked

    private void print_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_button1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new NewJFrame1().setVisible(true);
    }//GEN-LAST:event_print_button1ActionPerformed

    private void quantity_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity_textActionPerformed

    private void medicine_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicine_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicine_textActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s = search_fld.getText().toString();
        ResultSet rs;
        dtm.setRowCount(0);
        try {
            PreparedStatement stmt = con.prepareStatement("select * from drugs where Drugs_name like '%" + s + "%'");
            rs = stmt.executeQuery();
            while (rs.next()) {
                drugsID.add(rs.getInt(1));
                dtm.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getDouble(3), rs.getInt(4), rs.getDate(5), rs.getDate(6), rs.getString(7)});
                medicine_table.setModel(dtm);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "connection failed");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void fillTable() {
        try {
            PreparedStatement sm = con.prepareStatement("select * from drugs ");
            ResultSet rs = sm.executeQuery();
            dtm.setRowCount(0);
            while (rs.next()) {
                drugsID.add(rs.getInt(1));
                dtm.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getDouble(3), rs.getInt(4), rs.getDate(5), rs.getDate(6), rs.getString(7)});
                medicine_table.setModel(dtm);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddMedcine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbill_button;
    private javax.swing.JTextArea bill_list_text;
    private javax.swing.JTextField billid_text;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable medicine_table;
    private javax.swing.JTextField medicine_text;
    private javax.swing.JButton print_button;
    private javax.swing.JButton print_button1;
    private javax.swing.JTextField quantity_text;
    private javax.swing.JTextField search_fld;
    // End of variables declaration//GEN-END:variables
}
